#!/bin/bash
# Menu For Script
# Edition : Stable Edition V15.7.1
# Author  : Server Premium VIP
# (C) Copyright 2023-2024
# My Telegram : https://t.me/ServerPremiumVIP

MYIP=$(curl https://ipinfo.io/ip)
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"

clear

function notif_clearcache() {
    CHATID="$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)"
    KEY=""$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)""
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="Installasi VPN Script Stable V15.7.1
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  ⚠️CLEAR CACHE NOTIF⚠️</b>
<b>     Clear Cache VPS</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Clear Cache Done</code>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>BY BOT : https://t.me/ServerPremiumVIP</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function clear_ram_cache() {
    echo "Clearing RAM Cache..."
    sync; echo 1 > /proc/sys/vm/drop_caches
    echo "RAM Cache cleared."
}

function clear_disk_cache() {
    echo "Clearing Disk Cache..."
    sync; echo 2 > /proc/sys/vm/drop_caches
    echo "Disk Cache cleared."
}

echo "Checking VPS"
clear
echo ""
echo ""
echo -e "[ \033[32mInfo\033[0m ] Clear RAM Cache"
clear_ram_cache
sleep 3
echo -e "[ \033[32mInfo\033[0m ] Clear Disk Cache"
clear_disk_cache
notif_clearcache
echo ""
echo -e " ${GREEN} Back to menu in 2 sec ${NC}"
sleep 1
menu
